apiVersion: run.tanzu.vmware.com/v1alpha1 #TKG API endpoint 
kind: TanzuKubernetesCluster #required parameter 
metadata: 
  name: jenkins-cluster #cluster name, user defined 
  namespace: productivity-tools #supervisor namespace 
spec: 
  distribution: 
    version: 1.20.2 #resolved kubernetes version 
  topology: 
    controlPlane: 
      count: 1 #number of control plane nodes 
      class: best-effort-small #vmclass for control plane nodes 
      storageClass: k8s-policy #storageclass for control plane
    workers: 
      count: 1 #number of worker nodes 
      class: best-effort-small #vmclass for worker nodes 
      storageClass: k8s-policy #storageclass for worker nodes