---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-robot
  # namespace: JENKINS_ROBOT_NAMESPACE_NAME
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-robot-role-binding
  # namespace: JENKINS_ROBOT_NAMESPACE_NAME
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins-robot
  # namespace: JENKINS_ROBOT_NAMESPACE_NAME