apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkinspsp:privileged
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - POD_SECURITY_POLICY_NAME
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins:psp:privileged
roleRef:
  kind: ClusterRole
  name: jenkinspsp:privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:jenkins
  apiGroup: rbac.authorization.k8s.io
# Authorize specific service accounts (not recommended):
# - kind: ServiceAccount
#   name: jenkins-sa
#   namespace: jenkins