apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: jenkins-pvc1
  namespace: jenkins
spec:
 storageClassName: JENKINS_PVC_STORAGE_CLASS_NAME
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 4Gi