apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: jenkins-pvc1
  namespace: jenkins
spec:
 storageClassName: k8s-policy
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 4Gi