---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-role
  namespace: jenkins
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create","delete","get","list","patch","watch","update"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create","delete","get","list","patch","watch","update"]
- apiGroups: ["apps","extensions"]
  resources: ["deployments"]
  verbs: ["create","delete","get","list","patch","Watch","update"]
- apiGroups: [""]
  resources: ["services","endpoints"]
  verbs: ["create","delete","get","list","patch","watch","update"]
- apiGroups: [""]
  resources: ["ingresses"]
  verbs: ["create","delete","get","list","patch","update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create","patch","watch","list","get","delete"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["list","watch","get"]
- apiGroups: ["extensions"]
  resources: ["ingresses/status"]
  verbs: ["update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-role
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: jenkins